### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by jepunband** [M4cs/traxss#27]
[*] Running XSS Scan [*]
Traceback (most recent call last):
  File "traxss.py", line 6, in <module>
    menu.start()
  File "/home/jb/gh/traxss/traxss/core/menu.py", line 163, in start
    scanner.run_on_url()
  File "/home/jb/gh/traxss/traxss/core/scanner.py", line 128, in run_on_url
    self.driver = webdriver.Chrome(chrome_options=options)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevghActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

$chromedriver -v
ChromeDriver 78.0.3904.105 (60e2d8774a8151efa6a00b1f358371b1e0e07ee2-refs/branch-heads/3904@{#877})

**Comment by ch4r13** [comment]
I have this problem too,
```
chromedriver -v                                                              
ChromeDriver 97.0.4692.99 (d740da257583289dbebd2eb37e8668928fac5ead-refs/branch-heads/4692@{#1461})
```

**Comment by jpsanchezl10** [comment]
same , someone managed to fix it ?
chromedriver -v
ChromeDriver 112.0.5615.49 (bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936})
